(function(g){var window=this;var ewa=function(a,b,c,d){var e=b.dc();g.T(a.element,"ytp-suggestion-set",!!e.videoId);var f=b.getPlaylistId();d=b.bc(c,d?d:"mqdefault.jpg");var k=b instanceof g.jP?g.pW(b.lengthSeconds):null,l=!!f,f=l&&"RD"==g.gR(f).type,m=b instanceof g.jP?b.Ba:null;c={title:b.title,author:b.author,author_and_views:e.shortViewCount?b.author+" \u2022 "+e.shortViewCount:b.author,watch:g.U("YTP_WATCH_VIDEO_OR_PLAYLIST",{TITLE:b.title},b.title),duration:k,url:b.un(c),is_live:m,is_list:l,is_mix:f,background:d?"background-image: url("+
d+")":""};b instanceof g.iR&&(c.playlist_length=b.getLength());a.update(c)},P7=function(a,b){g.mW.call(this,{H:"div",
ca:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.o=a;this.N=!1},Q7=function(a){var b={H:"span",
M:"ytp-upnext-top",K:[{H:"span",M:"ytp-upnext-header",K:[g.U("YTP_PLAYLIST_UP_NEXT")]},{H:"span",M:"ytp-upnext-title",K:["{{title}}"]},{H:"span",M:"ytp-upnext-author",K:["{{author}}"]}]},c={href:"{{url}}","aria-label":g.U("YTP_AUTOPLAY_NEXT")},b={H:"div",M:"ytp-upnext",R:{"aria-label":"{{watch}}"},K:[{H:"div",M:"ytp-cued-thumbnail-overlay-image",R:{style:"{{background}}"}},b,{H:"a",M:"ytp-upnext-autoplay-icon",R:c,K:[{H:"svg",R:{height:"100%",version:"1.1",viewBox:"0 0 98 98",width:"100%"},K:[{H:"circle",
M:"ytp-svg-autoplay-circle",R:{cx:"49",cy:"49",fill:"#000","fill-opacity":"0.8",r:"48"}},{H:"circle",M:"ytp-svg-autoplay-ring",R:{cx:"-49",cy:"49","fill-opacity":"0",r:"46.5",stroke:"#FFFFFF","stroke-dasharray":"293","stroke-dashoffset":"-293","stroke-width":"4",transform:"rotate(-90)"}},{H:"polygon",M:"ytp-svg-autoplay-triangle",R:{fill:"#fff",points:"32,27 72,49 32,71"}}]}]},{H:"span",M:"ytp-upnext-bottom",K:[{H:"span",M:"ytp-upnext-cancel"},{H:"span",M:"ytp-upnext-paused",K:[g.U("YTP_AUTOPLAY_PAUSED_3")]}]},
{H:"span",M:"ytp-upnext-close"}]};g.Y.call(this,b);this.B=null;c=this.va["ytp-upnext-cancel"];b=this.va["ytp-upnext-close"];this.B=new g.Y({H:"button",ca:["ytp-upnext-cancel-button","ytp-button"],R:{tabindex:0,"aria-label":g.U("YTP_AUTOPLAY_CANCEL")},K:[g.U("YTP_CANCEL")]});g.M(this,this.B);this.B.U("click",this.FA,this);this.B.Ea(c);c=new g.Y({H:"button",ca:["ytp-upnext-close-button","ytp-button"],R:{"aria-label":g.U("YTP_AUTOPLAY_CANCEL")}});g.M(this,c);c.U("click",this.FA,this);c.Ea(b);this.o=
a;this.J=this.va["ytp-svg-autoplay-ring"];this.F=this.D=this.A=this.C=null;this.G=new g.tt(this.Km,5E3,this);g.M(this,this.G);this.I=0;this.P(this.va["ytp-upnext-autoplay-icon"],"click",this.mQ);this.CA();this.P(a,"autonavvisibility",this.CA);this.P(a,"mdxnowautoplaying",this.CP);this.P(a,"mdxautoplaycanceled",this.DP);this.P(a,"mdxautoplayupnext",this.JC);3==this.o.Ya()&&(a=(a=g.jV(g.eV(this.o)))?a.LH():null)&&this.JC(a)},fwa=function(a,b){a.C=b;
ewa(a,b,g.X(a.o),"hqdefault.jpg")},R7=function(a,b){a.A||(g.nG("a11y-announce",g.U("YTP_PLAYLIST_UP_NEXT")+" "+a.C.title),a.I=(0,g.AG)(),a.A=new g.tt((0,g.z)(a.Rp,a,b),25),a.Rp(b));
g.Kp(a.element,"ytp-upnext-autoplay-paused")},T7=function(a){S7(a);
a.I=(0,g.AG)();a.Rp();g.S(a.element,"ytp-upnext-autoplay-paused")},S7=function(a){a.A&&(a.A.dispose(),a.A=null)},gwa=function(a){P7.call(this,a,"subscribecard-endscreen");
var b=a.ga();this.A=new g.Y({H:"div",M:"ytp-subscribe-card",K:[{H:"img",M:"ytp-author-image",R:{src:b.profilePicture}},{H:"div",M:"ytp-subscribe-card-right",K:[{H:"div",M:"ytp-author-name",K:[b.author]},{H:"div",M:"html5-subscribe-button-container"}]}]});g.M(this,this.A);this.A.Ea(this.element);this.B=new g.M1(g.U("YTP_SUBSCRIBE"),null,g.U("YTP_UNSUBSCRIBE"),null,!0,!1,b.Hl,b.subscribed,"trailer-endscreen",null,null,a);g.M(this,this.B);this.B.Ea(this.A.va["html5-subscribe-button-container"]);this.hide()},
U7=function(a){var b=g.X(a),b=b.o&&!b.F;
g.Y.call(this,{H:"a",M:"ytp-videowall-still",R:{href:"{{url}}",target:b?"_blank":"","aria-label":"{{watch}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},K:[{H:"div",M:"ytp-videowall-still-image",R:{style:"{{background}}"}},{H:"span",M:"ytp-videowall-still-info",K:[{H:"span",M:"ytp-videowall-still-info-bg",K:[{H:"span",M:"ytp-videowall-still-info-content",R:g.VE||g.Xe?{style:"will-change: opacity"}:void 0,K:[{H:"span",M:"ytp-videowall-still-info-title",K:["{{title}}"]},
{H:"span",M:"ytp-videowall-still-info-author",K:["{{author_and_views}}"]},{H:"span",M:"ytp-videowall-still-info-live",K:[g.U("YTP_LIVE")]},{H:"span",M:"ytp-videowall-still-info-duration",K:["{{duration}}"]}]}]}]},{H:"span",ca:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],K:[{H:"span",M:"ytp-videowall-still-listlabel-icon"},g.U("YTP_PLAYLIST"),{H:"span",M:"ytp-videowall-still-listlabel-length",K:[" (",{H:"span",K:["{{playlist_length}}"]},")"]}]},{H:"span",ca:["ytp-videowall-still-listlabel-mix",
"ytp-videowall-still-listlabel"],K:[{H:"span",M:"ytp-videowall-still-listlabel-mix-icon"},g.U("YTP_MIX"),{H:"span",M:"ytp-videowall-still-listlabel-length",K:[" (50+)"]}]}]});this.B=b;this.o=a;this.A=null;this.U("click",this.C);this.U("keypress",this.D);if(g.X(a).da){a=a.app.ea;b=this.element;g.gb(a.g,b);g.kb(a.g,b);var c=String(a.G++);b.setAttribute("data-visual-id",c);g.Se(this,(0,g.z)(a.F,a,b))}},V7=function(a){P7.call(this,a,"videowall-endscreen");
this.aa=a;this.G=0;this.B=[];this.I=this.D=this.C=null;this.J=this.V=!1;this.F=new g.WF(this);g.M(this,this.F);this.L=new g.tt(g.Ba(g.S,this.element,"ytp-show-tiles"),0);g.M(this,this.L);var b=new g.Y({H:"button",ca:["ytp-button","ytp-endscreen-previous"],R:{"aria-label":g.U("YTP_PREVIOUS")},K:[g.YD()]});g.M(this,b);b.Ea(this.element);b.U("click",this.eM,this);this.O=new g.NV({H:"div",M:"ytp-endscreen-content"});g.M(this,this.O);this.O.Ea(this.element);b=new g.Y({H:"button",ca:["ytp-button","ytp-endscreen-next"],
R:{"aria-label":g.U("YTP_NEXT")},K:[g.ZD()]});g.M(this,b);b.Ea(this.element);b.U("click",this.dM,this);this.A=new Q7(a);g.M(this,this.A);g.GV(this.o,this.A.element,4);this.hide()},W7=function(a){return g.HV(a.o)&&a.Vp()&&!a.I},hwa=function(a){return(0,g.I)(a.hg,function(a){return g.e_(a)})},iwa=function(a,b,c){return 0==b&&a.C.length&&2<=c/2&&2<=c/2&&g.X(a.o).experiments.g("video_wall_emphasize_first")?4:2},X7=function(a){var b=a.ys();
b!=a.V&&(a.V=b,a.o.X("autonavvisibility"))},Y7=function(a){g.hW.call(this,a);
g.UD({});this.o=null;this.isAvailable=!0;this.A=new g.WF(this);g.M(this,this.A);this.B=g.X(a);jwa(a)?this.o=new V7(this.g):this.B.ra?this.o=new gwa(this.g):this.o=new P7(this.g);g.M(this,this.o);g.GV(this.g,this.o.element,4);this.OB();this.A.P(a,"videodatachange",this.OB,this);this.A.P(a,"crn_endscreen",this.GL,this);this.A.P(a,"crx_endscreen",this.HL,this)},jwa=function(a){a=g.X(a);
return a.Pc&&!a.ra};g.p(P7,g.mW);P7.prototype.create=function(){this.N=!0};
P7.prototype.destroy=function(){this.N=!1};
P7.prototype.Vp=function(){return!1};
P7.prototype.ys=function(){return!1};g.p(Q7,g.Y);g.h=Q7.prototype;g.h.Km=function(){this.D&&(this.G.stop(),this.Ca(this.F),this.F=null,this.D.close(),this.D=null)};
g.h.CA=function(){g.TV(this,g.fV(this.o))};
g.h.dQ=function(){window.focus();this.Km()};
g.h.hide=function(){g.Y.prototype.hide.call(this)};
g.h.Rp=function(a){a=a||g.X(this.o).experiments.o("autoplay_time")||1E4;var b=Math.min((0,g.AG)()-this.I,a);a=Math.min(b/a,1);this.J.setAttribute("stroke-dashoffset",-293*(a+1));1<=a&&3!=this.o.Ya()?this.select(!0):this.A&&this.A.start()};
g.h.select=function(a){a=void 0===a?!1:a;var b=g.X(this.o);if(b.experiments.g("autonav_notifications")&&a&&window.Notification&&window.document.hasFocus){var c=window.Notification.permission;g.tV(this.o,"xwebnotifications",{permission:c});"default"==c?window.Notification.requestPermission():"granted"!=c||window.document.hasFocus()||(c=this.C.dc(),this.Km(),this.D=new window.Notification(g.U("YTP_PLAYLIST_UP_NEXT"),{body:c.title,icon:c.bc(b)}),this.F=this.P(this.D,"click",this.dQ),this.G.start())}S7(this);
this.o.wj(!1,a)};
g.h.mQ=function(a){!g.Ee(this.B.element,g.MF(a))&&g.PZ(a,this.o)&&this.select()};
g.h.FA=function(){g.uV(this.o,"autonavcancel");g.hV(this.o,!0)};
g.h.CP=function(a){this.o.Ya();this.show();R7(this,a)};
g.h.JC=function(a){this.o.Ya();this.C&&this.C.dc().videoId==a.dc().videoId||fwa(this,a)};
g.h.DP=function(){this.o.Ya();S7(this);this.hide()};
g.h.W=function(){S7(this);this.Km();g.Y.prototype.W.call(this)};g.p(gwa,P7);g.p(U7,g.Y);U7.prototype.Lj=function(){var a=this.A.dc().videoId,b=this.A.getPlaylistId();g.x2(this.o.app,a,this.A.Vd,b,void 0,void 0)};
U7.prototype.C=function(a){g.KV(this.o,this.element);g.PZ(a,this.o,this.B,this.A.Vd||void 0)&&this.Lj()};
U7.prototype.D=function(a){switch(a.keyCode){case 13:case 32:g.RF(a)||(this.Lj(),g.TF(a))}};g.p(V7,P7);g.h=V7.prototype;g.h.create=function(){P7.prototype.create.call(this);var a=this.o.ga();a&&(this.C=hwa(a),this.D=a);this.th();this.F.P(this.o,"appresize",this.th);this.F.P(this.o,"videodatachange",this.fM);this.F.P(this.o,"autonavchange",this.Cz);this.F.P(this.o,"autonavcancel",this.cM);this.F.P(this.element,"transitionend",this.qR)};
g.h.destroy=function(){g.YF(this.F);g.Ue(this.B);this.B=[];this.C=null;P7.prototype.destroy.call(this);g.Kp(this.element,"ytp-show-tiles");this.L.stop()};
g.h.Vp=function(){return 1!=this.D.autonavState};
g.h.show=function(){P7.prototype.show.call(this);g.Kp(this.element,"ytp-show-tiles");g.X(this.o).isMobile?g.ut(this.L):this.L.start();(this.J||this.I&&this.I!=this.D.clientPlaybackNonce)&&g.hV(this.o,!1);var a=W7(this);g.HV(this.o)&&g.X(this.o).experiments.g("ui_logging")&&g.tV(this.o,"end",{cancelButtonShow:a?"1":"0",state:this.Vp()?"enabled":"disabled"});a?(X7(this),2==this.D.autonavState?g.X(this.o).experiments.g("fast_autonav_in_background")&&3==this.o.Vn()?this.A.select(!0):R7(this.A):3==this.D.autonavState&&
T7(this.A)):(g.hV(this.o,!0),X7(this))};
g.h.hide=function(){P7.prototype.hide.call(this);T7(this.A);X7(this)};
g.h.qR=function(a){g.MF(a)==this.element&&this.th()};
g.h.th=function(){if(this.C&&this.C.length){g.S(this.element,"ytp-endscreen-paginate");for(var a=g.Dh(this.element),b=a.width/a.height,c=96/54,d=2,e=2,f=Math.max(a.width/96,2),k=Math.max(a.height/54,2),l=this.C.length,m=Math.pow(2,2),n=l*m,q=iwa(this,0,k),r=iwa(this,1,k),n=n+(Math.pow(q,2)-m),n=n+(Math.pow(r,2)-m),n=n-m;0<n&&(d<f||e<k);){var w=d/2,A=e/2,C=d<=f-2&&n>=A*m,B=e<=k-2&&n>=w*m;if((w+1)/A*c/b>b/(w/(A+1)*c)&&B)n-=w*m,e+=2;else if(C)n-=A*m,d+=2;else if(B)n-=w*m,e+=2;else break}c=!1;f=2+q;n>=
3*m&&6>=l*m-n&&(e>=f||d>=f)&&2>=r&&(c=!0);m=96*d;n=54*e;b=m/n<b?a.height/n:a.width/m;b=Math.min(b,2);m*=b;n*=b;m*=g.Pd(a.width/m||1,1,1.21);n*=g.Pd(a.height/n||1,1,1.21);m=Math.floor(Math.min(a.width,m));n=Math.floor(Math.min(a.height,n));a=this.O.element;g.Ch(a,m,n);g.kh(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});fwa(this.A,this.C[0]);g.T(this.element,"ytp-endscreen-takeover",W7(this));X7(this);m+=4;n+=4;b=0;f=!1;for(k=0;k<d;k++)for(w=0;w<e;w++)if(A=2<r&&1<=b&&!f?b+1:b,C=0,c&&k>=d-2&&w>=e-2?C=
1:0==w%2&&0==k%2&&(w<q&&k<q?0==w&&0==k&&(C=q):2<r&&w>=e-r&&k>=d-r?w==e-r&&k==d-r&&(f=!0,A=1,C=r):C=2),A=g.Qd(A+this.G,l),0!=C){B=this.B[b];B||(B=new U7(this.o),this.B[b]=B,a.appendChild(B.element));var P=Math.floor(n*w/e),ba=Math.floor(m*k/d),Xa=Math.floor(n*(w+C)/e)-P-4,pb=Math.floor(m*(k+C)/d)-ba-4;g.rh(B.element,ba,P);g.Ch(B.element,pb,Xa);g.kh(B.element,"transitionDelay",(w+k)/20+"s");g.T(B.element,"ytp-videowall-still-mini",1==C);g.T(B.element,"ytp-videowall-still-large",2<C);C=B;A=this.C[A];
C.A=A;ewa(C,A,g.X(C.o),g.Ip(C.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg");B=A.Vd;A=C.o;g.X(A).da&&(A=A.app.ea,C=C.element,B=B&&B.itct,P=C.getAttribute("data-visual-id"),g.gb(A.g,C),g.IV(A,"onLogServerVeCreated",{id:P,tracking_params:B}));b++}g.T(this.element,"ytp-endscreen-paginate",b<l);for(d=this.B.length-1;d>=b;d--)e=this.B[d],g.xe(e.element),g.Te(e);this.B.length=b}};
g.h.fM=function(){var a=this.o.ga();this.D!=a&&(this.G=0,this.C=hwa(a),this.D=a,this.th())};
g.h.dM=function(){this.G+=this.B.length;this.th()};
g.h.eM=function(){this.G-=this.B.length;this.th()};
g.h.UJ=function(){return!!this.A.A};
g.h.Cz=function(a){1==a?(this.J=!1,this.I=this.D.clientPlaybackNonce,S7(this.A),this.g&&this.th()):(this.J=!0,this.g&&W7(this)&&(2==a?R7(this.A):3==a&&T7(this.A)))};
g.h.cM=function(a){if(a){for(a=0;a<this.B.length;a++)g.LV(this.aa,this.B[a].element,!0);this.Cz(1)}else this.I=null,this.J=!1;this.th()};
g.h.ys=function(){return this.g&&W7(this)};g.p(Y7,g.hW);g.h=Y7.prototype;g.h.zz=function(){var a=this.g.ga(),b=!jwa(this.g)||!(!a.hg||!a.hg.length),a=g.EP(a,"ypc_module"),c=g.y2(this.g.app);return(b||!1)&&!a&&!c};
g.h.yz=function(){return this.o.ys()};
g.h.RJ=function(){return this.yz()?this.o.UJ():!1};
g.h.W=function(){g.CV(this.g,"endscreen");g.hW.prototype.W.call(this)};
g.h.load=function(){g.hW.prototype.load.call(this);this.o.show();g.X(this.g).ra&&.01>Math.random()&&g.tV(this.g,"end",{trailerEndscreenShow:1})};
g.h.unload=function(){g.hW.prototype.unload.call(this);this.o.hide();this.o.destroy();this.isAvailable=!1};
g.h.GL=function(a){this.zz()&&(this.o.N||this.o.create(),"load"==a.getId()&&this.load())};
g.h.HL=function(a){"load"==a.getId()&&this.loaded&&this.unload()};
g.h.OB=function(){g.CV(this.g,"endscreen");var a=Math.max(1E3*(this.g.ga().lengthSeconds-10),0),a=new g.wJ(a,0x8000000000000,{id:"preload",namespace:"endscreen"}),b=new g.wJ(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});g.zV(this.g,[a,b])};g.wZ.endscreen=Y7;})(_yt_player);
