name: swlatinx
location: .
longname: 'Startup Weekend Latinx in Tech'
layout: bootstrap
author: techqueria
description: 'Join us for the 1st ever national Startup Weekend Latinx in Tech!'
version: 0.18.0
dest: docs
