name: swlatinx
location: .
longname: 'Startup Weekend Latinx in Tech'
layout: bootstrap
author: techqueria
description: 'Techstars Startup Weekend latinx in tech is happening the weekend of Sept 29, 2017'
version: 0.18.0
dest: docs
